@startuml MountNameAndDeviceIPDoesnotExist
skinparam responseMessageBelowArrow true

title
MediatorManager /v1/provide-mediator-instance 
<back:cadetblue><size:18>MountName And DeviceIP does not exist already</size></back>
end title

participant "MountingOrchestrator" as MO
participant "MediatorManager://v1/provide-mediator-instance" as MM
database "MediatorManager:APPDataFile" as AppData
participant "Ericsson MediatorInstanceManager" as EMIM
collections "All Other MediatorInstanceManager " as AMIM


MO -> MM : 
note right MO #PaleGreen
    { 
      mount-name: '513250011',
      device-ip: '1.2.3.4',
      device-model: 'MLTN'
    }
end note
activate MM #LightSteelBlue

rnote over MM #LightSteelBlue
    lists all the mediator instances
end note

MM -> EMIM : /v1/list-mediator-instances

MM -> AMIM : /v1/list-mediator-instances

hnote over MM #Pink
    If mount-name and device-ip does'nt exist
end note

rnote over MM #GreenYellow
    yes
end note

group To find the available mediator VMs in MM for the provided device-kind-name
    rnote over MM #LightSteelBlue
        Retrieves the list of mediator vm template
    end note

    AppData --\\o MM : <b>Retrieve the List of instance
    note right MM #LightGray
        [
        {
        "mediator-vm-template-name" : "EricssonMLTemplate",
        "vendor-name" : "Ericsson",
        "supported-device-kind" : ["MLTN","ML6600"],
        "engineering-limit" : 3600,
        <b>"paired-mediator-vm-list" : ["vmeric1"]
        },
        <b> . . .
        <b> . . .
        ]
    end note

    rnote over MM #LightSteelBlue
        Filter the "paired-mediator-vm-list" that supports the device-kind 
    end note

    hnote over MM #Pink
        Any Mediator VM available ? 
    end note

    rnote over MM #OrangeRed
        No
    end note

    MM -> MO : 517 Insufficient Storage

    rnote over MM #GreenYellow
        Yes
    end note

end

group To check engineering limit (repeat for all the filtered Mediator vm)
    rnote over MM #LightSteelBlue
        Calculate the available list of mediator instance 
        from the initial "/v1/list-mediator-instances"
    end note

    hnote over MM #Pink
        availableInstances < EngineeringLimit
    end note

    rnote over MM #OrangeRed
        no
    end note

    rnote over MM #LightSteelBlue
        Ignore this Mediator vm for Instance creation
    end note

    rnote over MM #GreenYellow
        yes
    end note

    rnote over MM #LightSteelBlue
        Consider this Mediator vm for Instance creation
    end note
end

hnote over MM #Pink
    any mediator instance available further
end note

rnote over MM #OrangeRed
    no
end note

MM -> MO : 517 Insufficient Storage

rnote over MM #GreenYellow
    yes
end note

group create mediator instance (If mediator instance creation fails, then repeat with the next available mediator vm)
        rnote over MM #LightSteelBlue
                If more than 1 mediator vm is available 
                then , 
                find the Mediator vm with the least number of instances
        end note

        MM -x EMIM : /v1/provide-mediator-instance
        EMIM -> MM : 404 NotFound
        MM -> MO : 503?

        MM -> EMIM : /v1/provide-mediator-instance
        activate EMIM #Grey
        hnote over EMIM #pink
        Authentication successful?
        end note
        rnote over EMIM #OrangeRed
        No
        end note
        EMIM -> MM : 401
        MM -> MO : 531?

        rnote over EMIM #GreenYellow
        Yes
        end note
        hnote over EMIM #pink
        mediator instance created successfully ?
        end note
        rnote over EMIM #OrangeRed
        NO
        end note
        EMIM -> MM : !=200
        MM -> MO : 532?

        rnote over EMIM #GreenYellow
        Yes
        end note

        EMIM -> MM : 200
        note right MM #LightGray
        {
        "device-name": '305251234'
        "device-kind-name": 'AGS_20'
        "mediator-instance-ip-address": '10.118.132.1'
        "mediator-instance-netconf-port": 1
        "device-ip-address": '10.118.133.1'
        }
        end note

        deactivate EMIM
        
        MM -> MO : 200 
        deactivate MM
        note right MO #LightGray
        {
        "mediator-instance-ip-address": '10.118.132.1'
        "mediator-instance-netconf-port": 1
        }
        end note
end

@enduml