@startuml MountNameExistWithDifferentIP
skinparam responseMessageBelowArrow true

title
MediatorManager /v1/provide-mediator-instance
<back:cadetblue><size:18>MountName already exist With a different device-iP</size></back>
<back:cadetblue><size:18>OR</size></back>
<back:cadetblue><size:18>device-ip already in use</size></back>
end title

participant "MountingOrchestrator" as MO
participant "MediatorManager://v1/provide-mediator-instance" as MM
database "MediatorManager:APPDataFile" as AppData
participant "Ericsson MediatorInstanceManager" as EMIM
collections "All Other MediatorInstanceManager " as AMIM


MO -> MM : 
note right MO #PaleGreen
    { 
      mount-name: '513250011',
      device-ip: '1.2.3.4',
      device-model: 'MLTN'
    }
end note
activate MM #LightSteelBlue

rnote over MM #LightSteelBlue
    lists all the mediator instances
end note

MM -> EMIM : /v1/list-mediator-instances

MM -> AMIM : /v1/list-mediator-instances
group mount-name already exist with a different device-ip
hnote over MM #Pink
    If mount-name already exist with a different device-ip
end note
rnote over MM #GreenYellow
    yes
end note

MM -> Device : PING the existing device-ip
hnote over MM #Pink
    If ping is successful for the existing device-ip?
end note
rnote over MM #OrangeRed
    yes
end note
MM -> MO : 409 conflict?
end
rnote over MM #GreenYellow
    No
end note

group device-ip already assigned to another mount-name
hnote over MM #Pink
    If incoming device-ip already assigned to another mount-name?
end note
rnote over MM #OrangeRed
    yes
end note
MM -> MO : 409 conflict?
end
rnote over MM #GreenYellow
    No
end note


== Further steps to create mediator instance from the diagram MountNameAndDeviceIPDoesnotExist.png ==
deactivate MM
MM -> MO
== ==


@enduml