@startuml MountNameWithCorrectIPExistForSameDeviceKindName
skinparam responseMessageBelowArrow true

title
MediatorManager /v1/provide-mediator-instance
<back:cadetblue><size:18>MountName and device-iP combination already exist</size></back>
end title

participant "MountingOrchestrator" as MO
participant "MediatorManager://v1/provide-mediator-instance" as MM
database "MediatorManager:APPDataFile" as AppData
participant "Ericsson MediatorInstanceManager" as EMIM
collections "All Other MediatorInstanceManager " as AMIM


MO -> MM : 
note right MO #PaleGreen
    { 
      mount-name: '513250011',
      device-ip: '1.2.3.4',
      device-model: 'MLTN'
    }
end note
activate MM #LightSteelBlue

rnote over MM #LightSteelBlue
    lists all the mediator instances
end note

MM -> EMIM : /v1/list-mediator-instances

MM -> AMIM : /v1/list-mediator-instances
group mount-name already exist with the incoming device-ip
hnote over MM #Pink
    If mount-name already exist with the incoming device-ip
end note
rnote over MM #GreenYellow
    yes
end note

rnote over MM #LightSteelBlue
    Formulate the request /v1/provide-mediator-instance
    for the mediator vm where the instance already exist
end note

MM -> EMIM : /v1/provide-mediator-instance
note right MM #LightGrey
    {
  "device-name": "513250011",
  "device-ip-address": "1.2.3.4",
  "device-kind-name": "MLTN"
}
end note

EMIM -> MM : 200 OK
note right MM #LightGray
        {
        "mediator-instance-ip-address": '10.118.132.1'
        "mediator-instance-netconf-port": 1
        }
end note


MM -> MO : 200 OK
note right MO #LightGray
        {
        "mediator-instance-ip-address": '10.118.132.1'
        "mediator-instance-netconf-port": 1
        }
end note
== Shall we also need to cover scenarios where EMIM sends responseCode!=200? ==
== ==

deactivate MM

@enduml