@startuml MountNameWithCorrectIPExistForDiffDeviceKindName
skinparam responseMessageBelowArrow true

title
MediatorManager /v1/provide-mediator-instance
<back:cadetblue><size:18>MountName and device-iP combination already exist</size></back>
<back:cadetblue><size:18>But, the mediator vm is not as per the "device-kind-name and mediator vm pairing" in the APP data</size></back>
end title


@enduml