@startuml 04_Flow_Substructured
skinparam componentStyle rectangle

  component [MO] as MO
  component [MM] as MM
   MO -[hidden]- MM
  component [...] as ODL
   MO -[hidden]- ODL
  component [CP] as ConnectionPreparation
   MM -[hidden]- ConnectionPreparation
  component [Device] as Device
   ConnectionPreparation -[hidden]- Device

  MO -> MM #SkyBlue : 2.2.2
    MM -> ConnectionPreparation #SkyBlue : 2.2.1c
      ConnectionPreparation -> Device #SkyBlue : 2.2.1a
      ConnectionPreparation -> Device #SkyBlue : 2.2.1b
  MO -> ODL #SkyBlue : 2.2.3

@enduml