@startuml CreateMediatorVmTemplate
skinparam responseMessageBelowArrow true

title
MediatorManager /v1/create-mediator-vm-template
end title

participant "OperationsTeam" as OT
participant "MM://v1/create-mediator-vm-template" as MM
database "ElasticSearch" as ES
database "MM:ConfigFile" as ConfigFile

OT -> MM : 
note right OT
  {
      "mediator-vm-template-name" : "emiv", [pattern: '^([a-z]{2,6})$']
      "vendor-name" : "Ericsson",
      "supported-device-kind-list" : ["MLTN", "ML6352"],
      "engineering-limit" : 2000,
      "provide-mediator-instance-operation-name" : "/v1/provide-mediator-instance",
      "dismantle-mediator-instance-operation-name" :"/v1/dismantle-mediator-instance",
      "list-mediator-instance-operation-name" :"/v1/list-mediator-instance"
  }
end note
activate MM #LightSteelBlue

MM -> ES : GET ES//appdata/mediator-vm-template-list
MM <-- ES : [mediator-vm-template-list]

  note over MM
    IF mediatorVmTemplateName does not already exist
    THEN create new mediator VM template
  end note
  MM -> ES : POST new mediator vm template to ES//appdata/mediator-vm-template-list
  MM --> OT : 204 NoContent

  note over MM
    ELSE terminate with error code
  end note
  MM --> OT : 409 Conflict

@enduml